import { defineConfig } from '@pandacss/dev';
import {
  colors,
  fontSizes,
  fontWeights,
  fonts,
  lineHeights,
  radii,
  space,
} from '@beefreguglia/beef-ui--tokens';

export default defineConfig({
  preflight: true,
  include: [
    './src/**/*.{ts,tsx,js,jsx}',
    './pages/**/*.{ts,tsx,js,jsx}',
    "./node_modules/@beefreguglia/beef-ui--react/src/**/*.tsx'",
  ],
  exclude: [],
  theme: {
    tokens: {
      colors: {
        $white: { value: colors.white },
        $black: { value: colors.black },

        $neutralGray50: { value: colors.neutralGray50 },
        $neutralGray100: { value: colors.neutralGray100 },
        $neutralGray200: { value: colors.neutralGray200 },
        $neutralGray300: { value: colors.neutralGray300 },
        $neutralGray400: { value: colors.neutralGray400 },
        $neutralGray500: { value: colors.neutralGray500 },
        $neutralGray600: { value: colors.neutralGray600 },
        $neutralGray700: { value: colors.neutralGray700 },
        $neutralGray800: { value: colors.neutralGray800 },
        $neutralGray900: { value: colors.neutralGray900 },

        $gray50: { value: colors.gray50 },
        $gray100: { value: colors.gray100 },
        $gray200: { value: colors.gray200 },
        $gray300: { value: colors.gray300 },
        $gray400: { value: colors.gray400 },
        $gray500: { value: colors.gray500 },
        $gray600: { value: colors.gray600 },
        $gray700: { value: colors.gray700 },
        $gray800: { value: colors.gray800 },
        $gray900: { value: colors.gray900 },

        $blue50: { value: colors.blue50 },
        $blue100: { value: colors.blue100 },
        $blue200: { value: colors.blue200 },
        $blue300: { value: colors.blue300 },
        $blue400: { value: colors.blue400 },
        $blue500: { value: colors.blue500 },
        $blue600: { value: colors.blue600 },
        $blue700: { value: colors.blue700 },
        $blue800: { value: colors.blue800 },
        $blue900: { value: colors.blue900 },

        $darkBlue50: { value: colors.darkBlue50 },
        $darkBlue100: { value: colors.darkBlue100 },
        $darkBlue200: { value: colors.darkBlue200 },
        $darkBlue300: { value: colors.darkBlue300 },
        $darkBlue400: { value: colors.darkBlue400 },
        $darkBlue500: { value: colors.darkBlue500 },
        $darkBlue600: { value: colors.darkBlue600 },
        $darkBlue700: { value: colors.darkBlue700 },
        $darkBlue800: { value: colors.darkBlue800 },
        $darkBlue900: { value: colors.darkBlue900 },

        $darkerBlue50: { value: colors.darkerBlue50 },
        $darkerBlue100: { value: colors.darkerBlue100 },
        $darkerBlue200: { value: colors.darkerBlue200 },
        $darkerBlue300: { value: colors.darkerBlue300 },
        $darkerBlue400: { value: colors.darkerBlue400 },
        $darkerBlue500: { value: colors.darkerBlue500 },
        $darkerBlue600: { value: colors.darkerBlue600 },
        $darkerBlue700: { value: colors.darkerBlue700 },
        $darkerBlue800: { value: colors.darkerBlue800 },
        $darkerBlue900: { value: colors.darkerBlue900 },

        $red50: { value: colors.red50 },
        $red100: { value: colors.red100 },
        $red200: { value: colors.red200 },
        $red300: { value: colors.red300 },
        $red400: { value: colors.red400 },
        $red500: { value: colors.red500 },
        $red600: { value: colors.red600 },
        $red700: { value: colors.red700 },
        $red800: { value: colors.red800 },
        $red900: { value: colors.red900 },

        $green50: { value: colors.green50 },
        $green100: { value: colors.green100 },
        $green200: { value: colors.green200 },
        $green300: { value: colors.green300 },
        $green400: { value: colors.green400 },
        $green500: { value: colors.green500 },
        $green600: { value: colors.green600 },
        $green700: { value: colors.green700 },
        $green800: { value: colors.green800 },
        $green900: { value: colors.green900 },

        $yellow50: { value: colors.yellow50 },
        $yellow100: { value: colors.yellow100 },
        $yellow200: { value: colors.yellow200 },
        $yellow300: { value: colors.yellow300 },
        $yellow400: { value: colors.yellow400 },
        $yellow500: { value: colors.yellow500 },
        $yellow600: { value: colors.yellow600 },
        $yellow700: { value: colors.yellow700 },
        $yellow800: { value: colors.yellow800 },
        $yellow900: { value: colors.yellow900 },
      },
      fontSizes: {
        $xxs: { value: fontSizes.xxs },
        $xs: { value: fontSizes.xs },
        $sm: { value: fontSizes.sm },
        $md: { value: fontSizes.md },
        $lg: { value: fontSizes.lg },
        $xl: { value: fontSizes.xl },
        $2xl: { value: fontSizes['2xl'] },
      },
      fontWeights: {
        $thin: { value: fontWeights.thin },
        $extraLight: { value: fontWeights.extraLight },
        $light: { value: fontWeights.light },
        $regular: { value: fontWeights.regular },
        $medium: { value: fontWeights.medium },
        $semiBold: { value: fontWeights.semiBold },
        $bold: { value: fontWeights.bold },
        $extraBold: { value: fontWeights.extraBold },
        $black: { value: fontWeights.black },
      },
      fonts: {
        $default: { value: fonts.default },
        $code: { value: fonts.code },
      },
      lineHeights: {
        $shorter: { value: lineHeights.shorter },
        $short: { value: lineHeights.short },
        $base: { value: lineHeights.base },
        $tall: { value: lineHeights.tall },
      },
      radii: {
        $px: { value: radii.px },
        $xxs: { value: radii.xxs },
        $xs: { value: radii.xs },
        $sm: { value: radii.sm },
        $md: { value: radii.md },
        $lg: { value: radii.lg },
        $full: { value: radii.full },
      },
      spacing: {
        $1: { value: space[1] },
        $2: { value: space[2] },
        $3: { value: space[3] },
        $4: { value: space[4] },
        $5: { value: space[5] },
        $6: { value: space[6] },
        $7: { value: space[7] },
        $8: { value: space[8] },
        $10: { value: space[10] },
        $12: { value: space[12] },
        $16: { value: space[16] },
        $20: { value: space[20] },
        $40: { value: space[40] },
        $64: { value: space[64] },
        $80: { value: space[80] },
      },
      sizes: {
        $1: { value: space[1] },
        $2: { value: space[2] },
        $3: { value: space[3] },
        $4: { value: space[4] },
        $5: { value: space[5] },
        $6: { value: space[6] },
        $7: { value: space[7] },
        $8: { value: space[8] },
        $10: { value: space[10] },
        $12: { value: space[12] },
        $16: { value: space[16] },
        $20: { value: space[20] },
        $40: { value: space[40] },
        $64: { value: space[64] },
        $80: { value: space[80] },
      },
    },
    extend: {
      keyframes: {
        slideIn: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        slideOut: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(0)' },
        },
      },
    },
  },

  emitPackage: true,
  jsxFramework: 'react',
  outdir: '@beefreguglia/beef-ui--react',
});
